
package lab.engr4790.jawxs.jaxws.nxtcommand;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NXTCommand", targetNamespace = "http://jawxs.engr4790.lab/jaxws/nxtcommand", wsdlLocation = "http://localhost:8084/Lab5PartC/NXTCommand?wsdl")
public class NXTCommand
    extends Service
{

    private final static URL NXTCOMMAND_WSDL_LOCATION;
    private final static WebServiceException NXTCOMMAND_EXCEPTION;
    private final static QName NXTCOMMAND_QNAME = new QName("http://jawxs.engr4790.lab/jaxws/nxtcommand", "NXTCommand");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/Lab5PartC/NXTCommand?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NXTCOMMAND_WSDL_LOCATION = url;
        NXTCOMMAND_EXCEPTION = e;
    }

    public NXTCommand() {
        super(__getWsdlLocation(), NXTCOMMAND_QNAME);
    }

    public NXTCommand(WebServiceFeature... features) {
        super(__getWsdlLocation(), NXTCOMMAND_QNAME);
    }

    public NXTCommand(URL wsdlLocation) {
        super(wsdlLocation, NXTCOMMAND_QNAME);
    }

    public NXTCommand(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NXTCOMMAND_QNAME);
    }

    public NXTCommand(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NXTCommand(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns NXTRobotWS
     */
    @WebEndpoint(name = "NXTCommandPort")
    public NXTRobotWS getNXTCommandPort() {
        return super.getPort(new QName("http://jawxs.engr4790.lab/jaxws/nxtcommand", "NXTCommandPort"), NXTRobotWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NXTRobotWS
     */
    @WebEndpoint(name = "NXTCommandPort")
    public NXTRobotWS getNXTCommandPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jawxs.engr4790.lab/jaxws/nxtcommand", "NXTCommandPort"), NXTRobotWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NXTCOMMAND_EXCEPTION!= null) {
            throw NXTCOMMAND_EXCEPTION;
        }
        return NXTCOMMAND_WSDL_LOCATION;
    }

}
